### ISSUE TITLE
How do you populating list objects??

### ISSUE THREAD

**Issue by trinadhkoya** [masudias/dynamic-recyclerview#1]
Seems like you are not populating any objects to adapter ??

**Comment by masudias** [comment]
I didn't quite understand your question. But anyway, if its related with populating the lists of objects you can check the functions in `Utilities` that I've used for populating the two lists. 

I've not populated any list inside the adapter. The lists are populated before passing it to the adapter. Please check the [wiki](https://github.com/comeondude/dynamic-recyclerview/wiki) for better understand about how this works.
