### ISSUE TITLE
Dynamic Recyrcleview 

### ISSUE THREAD

**Issue by anderson-scherdovski** [masudias/dynamic-recyclerview#3]
Is possible to do a recyclerview dynamic type in a for?

**Comment by masudias** [comment]
Didn't quite understand the question. Can you please explain a little? Yes it is possible to make every row customized and dynamic. In that case, you just have to handle different view types based on the position of your item in a list which is passed to the adapter of your RecyclerView.

**Comment by anderson-scherdovski** [comment]
I'm sorry if it's not clear why I do not speak English. is that in your example was added 2 of static examples but I wanted to add dynamically would it be possible?

**Comment by masudias** [comment]
Yes it is possible. You just have to handle the view types properly. It would be great if you could help me with your lists for example, so that I could help you in guiding how to populate them in your RecyclerView.

**Comment by anderson-scherdovski** [comment]
is that my lists are all the same, but with different data.

**Comment by masudias** [comment]
I see. Please ask a question in StackOverflow and give me the link of your question here. So that I can take a look at the problem you are facing. Thanks.
