### ISSUE TITLE
Implement in Kotlin

### ISSUE THREAD

**Issue by titiarimba** [masudias/dynamic-recyclerview#4]
Hi @masudias i just knew your project. can you explain me how to implement this dynamic-recyclerview in kotlin? cause i already search on StackOverflow there's nothing. thanks 👍

**Comment by masudias** [comment]
I think the Java code can be migrated to Kotlin without any hassle using Android Studio. I am not a Kotlin coder. I cannot help you with that. However, as I said earlier, the Java code can be migrated to Kotlin easily. Hope that helps!
